# PlantUML Editor


@startuml
skinparam monochrome true
skinparam defaultTextAlignment center

' Root node
agent "User Data" as goal

' Sub goals
agent "Abuse business logic" as bizlogic
agent "Brute Force" as bruteforce
agent "Gain DB access" as db

goal --> db



agent "sqli" as sqli
agent "Gain access to remote api" as remoteapi
agent "xss" as xss
agent "csrf" as csrf 
db --> sqli
db --> remoteapi
 

interface "and" as and
remoteapi --> and

agent "Authentication Bypass" as authbypass
agent "DNS Rebinding Attack" as dns
agent "Brute Force" as bruteforce
agent "Gain DB access" as db
and --> authbypass
and --> dns

' Abstraction (not going to model that)
cloud "attacker" as another
authbypass --> another
dns --> another
bruteforce --> another
sqli --> another
remoteapi --> bruteforce
remoteapi --> xss 
remoteapi --> bizlogic 
remoteapi --> csrf 
xss --> another
csrf --> another
bizlogic --> another
